- name: Install xclip
  ansible.builtin.package:
    name: xclip
    state: present

- name: Install & configure git
  ansible.builtin.include_tasks: git.yml

- name: Install & configure vim
  ansible.builtin.include_tasks: vim.yml

- name: Install & configure bat
  ansible.builtin.include_tasks: bat.yml

- name: Install fuzzy-finder
  become: yes
  ansible.builtin.package:
    name: fzf
    state: present

- name: Install & configure zsh
  ansible.builtin.include_tasks: zsh.yml
