- name: Install & configure tools
  ansible.builtin.include_tasks: 
    file: "{{ tool }}.yml"
  loop:
    - git
    - vim
    - bat
    - fzf
    - tmux
    - xclip
    - zsh
  loop_control:
    loop_var: tool
