- name: Install tmux
  become: yes
  ansible.builtin.package:
    name: tmux
    state: latest

- name: Create .tmux.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env['HOME'] }}/.tmux.conf"
